atashbaan/images/urls.py
from django.urls import path

from atashbaan.images.views import (
    image_delete_view,
    image_detail_view,
    image_list_view,
    image_process_view,
    image_upload_view,
)

app_name = "images"

urlpatterns = [
    path("", image_list_view, name="image_list"),
    path("<int:pk>/", image_detail_view, name="image_detail"),
    path("delete/<int:pk>/", image_delete_view, name="image_delete"),
    path("upload/", image_upload_view, name="image_upload"),
    path("process/", image_process_view, name="image_process"),
]

atashbaan/users/urls.py
from django.urls import path

from atashbaan.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("atashbaan.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("images/", include("atashbaan.images.urls", namespace="images")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

atashbaan/images/models.py
import datetime
import posixpath

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q

import pytz

User = get_user_model()


def user_uploads_path(instance, filename):
    date = datetime.datetime.now(tz=pytz.timezone("Asia/Tehran"))
    year = date.year
    month = date.month
    day = date.day

    dirname = f"images/{instance.user.id}/{instance.tag}/{year}/{month}/{day}/"

    return posixpath.join(dirname, filename)


class UnprocessedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(tag="unprocessed")


class ProcessedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(tag="processed")


class Image(models.Model):
    TAG_CHOICES = (("processed", "پردازش شده"), ("unprocessed", "پردازش نشده"))

    image = models.ImageField(
        "تصویر", upload_to=user_uploads_path, blank=False, null=False
    )
    tag = models.CharField(
        "برچسب", max_length=20, default="unprocessed", choices=TAG_CHOICES
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="images", verbose_name="کاربر"
    )

    created_at = models.DateTimeField("تاریخ ایجاد", auto_now_add=True)
    last_modified = models.DateTimeField("آخرین بروزرسانی", auto_now=True)

    objects = models.Manager()
    unprocessed = UnprocessedManager()
    processed = ProcessedManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["image"],
                condition=Q(tag="processed"),
                name="unique_processed_image",
            )
        ]
        ordering = [
            "created_at",
        ]

atashbaan/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse


class User(AbstractUser):
    """
    Default custom user model for Atashbaan.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField("نام و نام خانوادگی", blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

atashbaan/images/forms.py
from django.forms import CharField, Form, HiddenInput, ImageField, ModelForm

from .models import Image


class ImageUploadForm(ModelForm):
    image = ImageField(
        required=True,
        max_length=100,
        label="تصویر",
        help_text="لطفاً تصویر مورد نظر خود را از طریق این فرم بارگداری کنید.",
    )

    class Meta:
        model = Image
        fields = [
            "image",
        ]


class SaveProcessedImageForm(Form):
    def __init__(self, *args, **kwargs):
        super(SaveProcessedImageForm, self).__init__(*args, **kwargs)
        self.fields["image"] = CharField(required=False, widget=HiddenInput())

atashbaan/users/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

atashbaan/images/views.py
from base64 import b64decode
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.core.paginator import InvalidPage
from django.db.models.query import QuerySet
from django.http import (
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotFound,
    HttpResponseRedirect,
)
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.views.generic.base import ContextMixin, View

from atashbaan.images.forms import ImageUploadForm, SaveProcessedImageForm
from atashbaan.images.image_processor import fire_recognizer
from atashbaan.images.models import Image


# Create your views here.
class ImageUploadView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "images/image_upload.html"
    form_class = ImageUploadForm
    success_message = "تصویر با موفقیت بارگذاری شد."
    success_url = "/images/process/"

    def form_valid(self, form: Any) -> HttpResponse:
        form.instance.user = self.request.user
        form.instance.tag = "unprocessed"
        image = form.save(commit=False)
        image.save()

        return super().form_valid(form)


image_upload_view = ImageUploadView.as_view()


class ImageProcessView(LoginRequiredMixin, ContextMixin, View):
    template_name = "images/image_process.html"
    success_message = "تصویر پردازش شده با موفقیت ذخیره شد."
    save_form = SaveProcessedImageForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        user = self.request.user
        form = self.save_form()

        self.extra_context = {"user": user, "form": form}

        return super().get_context_data(**kwargs)

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        context = self.get_context_data()
        qd_image_pk = self.request.GET.get("image-pk")

        if qd_image_pk:
            try:
                img = Image.unprocessed.get(pk=qd_image_pk)
            except Image.DoesNotExist:
                return HttpResponseNotFound(render(request, "404.html"))
        else:
            try:
                img = Image.unprocessed.filter(user=context["user"]).latest(
                    "created_at"
                )
            except Image.DoesNotExist:
                return HttpResponseNotFound(render(request, "404.html"))

        if img.user == self.request.user:
            img_fp = img.image.path

            image = fire_recognizer(img_fp)

            context["form"].fields["image"].initial = image

            return render(request, self.template_name, context)
        else:
            return HttpResponseForbidden(render(request, "403.html"))

    def post(self, request, *args, **kwargs):
        user = self.request.user
        form = self.save_form(request.POST or None)
        qd_image_pk = self.request.GET.get("image-pk")

        if qd_image_pk:
            try:
                usr_image = user.images.get(pk=qd_image_pk)
            except Image.DoesNotExist:
                return HttpResponseNotFound(render(request, "404.html"))
        else:
            try:
                usr_image = user.images.latest("created_at")
            except Image.DoesNotExist:
                return HttpResponseNotFound(render(request, "404.html"))

        # file naming
        usr_image_name = usr_image.image.name
        full_file_name = usr_image_name.split("/")[-1]
        file_name = full_file_name.split(".")[0]
        ext = usr_image_name.split(".", 1)[1]

        if form.is_valid():
            img = form.cleaned_data["image"]

            image_file = ContentFile(
                b64decode(img), name=file_name + "-processed." + ext
            )

            image = Image(image=image_file)
            image.tag = "processed"
            image.user = self.request.user
            image.save()

            messages.success(self.request, self.success_message)
        else:
            context = self.get_context_data()
            context.update({"form": form})

            return render(request, self.template_name, context=context)

        return HttpResponseRedirect(reverse("images:image_list"))


image_process_view = ImageProcessView.as_view()


class ImageListView(LoginRequiredMixin, ListView):
    template_name = "images/image_list.html"
    model = Image
    paginate_by = 5
    paginate_orphans = 1
    context_object_name = "images"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Image.processed.filter(user=self.request.user)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        del context["object_list"]

        user = self.request.user

        unprocessed_images = Image.unprocessed.filter(user=self.request.user)
        unprocessed_page_size = self.get_paginate_by(unprocessed_images)
        if unprocessed_page_size:
            (
                unprocessed_paginator,
                unprocessed_page,
                unprocessed_images,
                unprocessed_is_paginated,
            ) = self.custom_paginate_queryset(unprocessed_images, unprocessed_page_size)
            context.update(
                {
                    "unprocessed_paginator": unprocessed_paginator,
                    "unprocessed_page_obj": unprocessed_page,
                    "unprocessed_is_paginated": unprocessed_is_paginated,
                    "unprocessed_images": unprocessed_images,
                    "user": user,
                }
            )
        else:
            context.update(
                {
                    "unprocessed_paginator": None,
                    "unprocessed_page_obj": None,
                    "unprocessed_is_paginated": False,
                    "unprocessed_images": unprocessed_images,
                    "user": user,
                }
            )

        return context

    def custom_paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(
            queryset,
            page_size,
            orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty(),
        )
        page_kwarg = "unprocessed-image-page"
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        try:
            page_number = int(page)
        except ValueError:
            if page == "last":
                page_number = paginator.num_pages
            else:
                raise Http404(
                    _("Page is not “last”, nor can it be converted to an int.")
                )
        try:
            page = paginator.page(page_number)
            return (paginator, page, page.object_list, page.has_other_pages())
        except InvalidPage as e:
            raise Http404(
                _("Invalid page (%(page_number)s): %(message)s")
                % {"page_number": page_number, "message": str(e)}
            )


image_list_view = ImageListView.as_view()


class ImageDetailView(LoginRequiredMixin, DetailView):
    template_name = "images/image_detail.html"
    model = Image
    context_object_name = "image"

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Image.objects.filter(user=self.request.user)

        return queryset

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        del context["object"]

        return context


image_detail_view = ImageDetailView.as_view()


class ImageDeleteView(DeleteView):
    model = Image
    context_object_name = "image"
    success_url = reverse_lazy("images:image_list")

    def form_valid(self, form):
        messages.success(self.request, "تصویر مورد نظر با موفقیت حذف شد.")

        return super().form_valid(form)


image_delete_view = ImageDeleteView.as_view()

atashbaan/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

atashbaan/templates/images/image_confirm_delete.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}
    تأیید حذف تصویر
{% endblock head_title %}

{% block inner %}
  <div class="row justify-content-md-center">
    <h1 class="text-center">تأیید حذف تصویر</h1>
  </div>
  <div class="row justify-content-md-center mt-3">
    <p class="text-center">آیا از حذف این تصویر اطمینان دارید؟</p>
  </div>
  <div class="row justify-content-md-center mt-3">
    <form class="text-center" method="post">
      {% csrf_token %}
      <button class="btn btn-danger w-100" type="submit">بله</button>
      <a class="btn btn-secondary w-100 my-3" href="{% url "images:image_detail" image.pk %}">بازگشت</a>
    </form>
  </div>
{% endblock inner %}

atashbaan/templates/images/image_detail.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}
    جزئیات
{% endblock head_title %}

{% block inner %}
    <div class="row justify-content-md-center mt-3">
        <div class="col-md-3">
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <h3 class="text-center">
                        اطلاعات تصویر:
                    </h3>
                </div>
            </div>
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <p class="text-center">
                        <strong id="strong-text">تاریخ ایجاد:</strong> {{ image.created_at }}
                    </p>
                </div>
            </div>
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <p class="text-center">
                        <strong id="strong-text">تگ:</strong> {{ image.get_tag_display }}
                    </p>
                </div>
            </div>
            {% if image.tag == "unprocessed" %}
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <form action="{% url "images:image_process" %}">
                        <input type="hidden" name="image-pk" value="{{ image.pk }}">
                        <button class="btn btn-success" type="submit">
                            پردازش
                        </button>
                    </form>
                </div>
            </div>
            {% endif %}
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <a class="btn btn-danger" href="{% url "images:image_delete" image.pk %}">
                        حذف
                    </a>
                </div>
            </div>
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto">
                    <a class="btn btn-primary" href="{% url "images:image_list" %}">
                        بازگشت به فهرست
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row justify-content-md-center mt-3">
                <div class="col-md-auto text-center">
                    <img class="rounded" src="{{ image.image.url }}" alt="image-{{ image.pk }}" style="max-width: 100%; height: auto;">
                </div>
            </div>
        </div>
    </div>
{% endblock inner %}

atashbaan/templates/images/image_list.html
{% extends "account/base.html" %}

{% block head_title %}
    فهرست تصاویر
{% endblock head_title %}

{% block inner %}
    <div class="row justify-content-md-center">
        <h1 class="text-center">فهرست تصاویر 
            <a id="header-link" href="{% url "users:detail" user.username %}">
                {{ user.name }}
            </a>
        </h1>
    </div>
    <div class="rounded border border-4 border-success my-3">
        <div class="row justify-content-md-center">
            <div class="col-md-auto px-5 py-5">
                <div class="row justify-content-md-center">
                    {% for image in images %}
                        <div class="col-sm-2 py-4">
                            <div class="card text-center">
                                <img
                                src="{{ image.image.url }}"
                                class="card-img-top"
                                alt="{{ image.image.name }}"
                                />
                                <div class="card-body">
                                    <h5 class="card-title"><span class="badge rounded-pill text-bg-success">{{ image.get_tag_display }}</span></h5>
                                    <p class="card-text"></p>
                                    <a href="{% url "images:image_detail" image.pk %}" class="btn btn-primary">جزئیات</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <div class="row justify-content-md-center">
                        <div class="d-flex justify-content-center my-4">
                            <div class="btn-group" role="group" aria-label="pagination">
                                {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-dark rounded">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                                        </svg>
                                    </a>
                                {% endif %}
                                <a href="!#" class="btn btn-outline-dark rounded mx-2">
                                    {{ page_obj.number }}
                                </a>
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-dark rounded">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                                        </svg>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="rounded border border-4 border-danger my-3">
        <div class="row justify-content-md-center">
            <div class="col-md-auto px-5 py-5">
                <div class="row justify-content-md-center">
                    {% for image in unprocessed_images %}
                        <div class="col-sm-2 py-4">
                            <div class="card text-center">
                                <img
                                src="{{ image.image.url }}"
                                class="card-img-top"
                                alt="{{ image.image.name }}"
                                />
                                <div class="card-body">
                                    <h5 class="card-title"><span class="badge rounded-pill text-bg-warning">{{ image.get_tag_display }}</span></h5>
                                    <p class="card-text"></p>
                                    <a href="{% url "images:image_detail" image.pk %}" class="btn btn-primary">جزئیات</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if unprocessed_is_paginated %}
                    <div class="row justify-content-md-center">
                        <div class="d-flex justify-content-center my-4">
                            <div class="btn-group" role="group" aria-label="pagination">
                                {% if unprocessed_page_obj.has_previous %}
                                    <a href="?unprocessed-image-page={{ unprocessed_page_obj.previous_page_number }}" class="btn btn-circle btn-outline-dark rounded">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                                        </svg>
                                    </a>
                                {% endif %}
                                <a href="#!" class="btn btn-outline-dark rounded mx-2">
                                    {{ unprocessed_page_obj.number }}
                                </a>
                                {% if unprocessed_page_obj.has_next %}
                                    <a href="?unprocessed-image-page={{ unprocessed_page_obj.next_page_number }}" class="btn btn-outline-dark rounded">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                                        </svg>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock inner %}

atashbaan/templates/images/image_process.html
{% extends "account/base.html" %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block head_title %}
    پردازش تصویر
{% endblock head_title %}

{% block inner %}
    <div class="row justify-content-md-center">
        <h1 class="text-center">پردازش تصویر</h1>
    </div>
    <div class="row justify-content-md-center mt-3">
        {% if form.image.value %}
            <div class="col-md-auto">
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto">
                        <h3 class="lead text-center">
                            نتیجه پردازش تصویر بارگذاری شده توسط کتابخانه تشخیص آتش به صورت زیر می‌باشد:
                        </h3>
                    </div>
                </div>
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto text-center">
                        <img src="data:image/png;base64,{{ form.image.value }}" id="processed-image" class="rounded" style="max-width: 50%; height: auto;" alt="processed-image">
                    </div>
                </div>
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto">
                        <p class="lead text-center">
                            آیا مایل به ذخیره‌سازی تصویر پردازش شده هستید؟
                        </p>
                    </div>
                </div>
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto">
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="mb-3">
                                <button class="btn btn-primary w-100" type="submit">بله</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-auto">
                        <a class="btn btn-primary" href="{% url "users:detail" user.username %}" role="button">خیر، بازگشت به ناحیه کاربری</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="col-md-auto">
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto">
                        <h3 class="lead text-center">
                            متأسفانه پردازش تصویر بارگذاری شده با مشکل روبرو شد، لطفاً این مورد را از طریق پشتیبانی پیگیری نمائید.
                        </h3>
                    </div>
                </div>
                <div class="row justify-content-md-center mt-3">
                    <div class="col-md-auto">
                        <a class="btn btn-primary" href="{% url "users:detail" user.username %}" role="button">بازگشت به ناحیه کاربری</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock inner %}

atashbaan/templates/images/image_upload.html
{% extends "account/base.html" %}

{% load crispy_forms_tags %}

{% block head_title %}
    بارگذاری تصویر
{% endblock head_title %}

{% block inner %}
    <div class="row justify-content-md-center">
        <h1 class="text-center">بارگذاری تصویر</h1>
    </div>
    <div class="row justify-content-md-center mt-3">
        <div class="col-md-auto">
          <form enctype='multipart/form-data' method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="mb-3">
              <button class="btn btn-primary w-100" type="submit">بارگذاری</button>
            </div>
          </form>
        </div>
    </div>
{% endblock inner %}